config/routes.rb
Rails.application.routes.draw do

  get 'about', to: 'pages#about', as: :about

  devise_for :users
  root to: 'burgers#index'

  resources :burgers, only: [:show, :new, :create, :destroy, :edit, :update] do
    resources :orders, only: [:new, :create]
  end

  resources :orders, only: [:index, :update] do
    collection do
      get "mine" , to: "orders#index_cooker_orders"
    end
  end

  namespace :admin do
    resources :burgers, only: [:index]
  end

end
# no destroy method on order, as we consider that a payed order cannot be canceled

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/burger.rb
class Burger < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :orders

  WEEK_DAYS = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"]

  validates :name, presence: true, uniqueness: { scope: :user, message:"already exist" }
  validates :quantity_max, presence: true, numericality: { greater_than: -1, message:"cannot be negative or null" }
  validates :opening_days, inclusion: { in: WEEK_DAYS, allow_blank: true }
  validates :price, presence: true, numericality: { greater_than: 0, message:"cannot be negative or null" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :burger
  belongs_to :user

  validates :quantity, presence: true, numericality: { greater_than: 0, message:"you cannot order less than 1 burger" }

end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :burgers
  has_many :orders, dependent: :destroy

  validates :address, presence: true
end

app/controllers/admin/burgers_controller.rb
class Admin::BurgersController < ApplicationController

  def index
    @burgers = []
    policy_scope(Burger).each do |burger|
      if burger.user == current_user
        @burgers << burger
      end
    end
    return @burgers
  end

  private

  def burger_params
    params.require(:burger).permit(:name, :description, :image_url, :price, :opening_days, :quantity_max, :published)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end


  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :address])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_burger, only: [:edit, :destroy, :update, :show]

  def index

    @burgers = policy_scope(Burger).where.not(quantity_max: 0).order(created_at: :desc)

    @users = User.where.not(latitude: nil, longitude: nil)

    @markers = @users.map do |user|
      if !user.burgers.empty?
        {
          lat: user.latitude,
          lng: user.longitude#,
          # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
        }
      end
    end
  end

  def show
    @markers = [
      {
        lat: @burger.user.latitude,
        lng: @burger.user.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      } ]
    @order = Order.new
  end


  def new
    @burger = Burger.new
    authorize @burger
  end

  def create
    @burger = Burger.new(burger_params)
    @burger.user = current_user
    authorize @burger
    if @burger.save
      redirect_to burger_path(@burger)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @burger.update(burger_params)
      redirect_to burger_path(@burger)
    else
      render :edit
    end
  end

  def destroy
    @burger.destroy
    redirect_to root_path
  end

  private

  def find_burger
    @burger = Burger.find(params[:id])
    authorize @burger
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def burger_params
    params.require(:burger).permit(:name, :description, :photo, :price, :quantity_max, :opening_days, :published)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  after_action :verify_authorized, except: [:index, :index_cooker_orders], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :index_cooker_orders], unless: :skip_pundit?


  def new
    # créer 1 instance d'order et 1 instance burger pour contruire le formulaire avec les champs nommés et le chemin nested
    @order = Order.new
    authorize @order
    @burger = Burger.find(params[:burger_id])
  end

  def create
    # cré 1 instance order en utilisant le hash quantité des params (sinon faudrait demander la clé du hash et l'affecter, plus compliqué..)
    @order = Order.new(order_params)
    authorize @order
    @order.user = current_user

    # burger_id et non pas id, parce qu'on a nested pour pouvoir récupérer l'id du burger

    @burger =  Burger.find(params[:burger_id])
    @order.burger = @burger
    if @order.quantity > @burger.quantity_max
      flash[:alert] = "You cannot order more than #{@burger.quantity_max}!"
      render 'burgers/show'
    else
      @order.total_price = @order.quantity * @burger.price
      @burger.quantity_max -= @order.quantity
      # il faut pernser à faire les strong params sinon c'est jamais sauvegarder en bdd et ca passe en else
      if @order.save
        @burger.save
        redirect_to orders_path()
      else
      # suffit juste d'indiquer le nom et comprend qu'il faut le chercher en local par défaut, sinon '../jfk/kljf/nom'
        render 'burgers/show'
      end
    end
  end

  def index
    # methode listant toutes les commandes
    # @orders = Order.all
    # methode listant toutes les commandes d'un utilisateur
    @orders = policy_scope(Order).where(user: current_user)
  end


  def index_cooker_orders
    # methode listant toutes les commandes
    # TODO : requete à améliorer !!!!!
    @orders = policy_scope(Order).joins(:burger).where(burgers: {user_id: current_user.id} )
    # orders.each do |order|
    #   authorize @order
    #   if order.burger.user_id == current_user.id
    #     @orders << order
    #   end
    # end
    # # methode listant toutes les commandes d'un utilisateur
    # return @orders
  end

  def update
    @order = Order.find(params[:id])
    authorize @order
    @order.delivered = true
    if @order.save
      redirect_to mine_orders_path()
    else
    # suffit juste d'indiquer le nom et comprend qu'il faut le chercher en local par défaut, sinon '../jfk/kljf/nom'
      render 'orders/index_cooker_orders'
    end
  end

  def show
    @order = Order.find(params[:id])
    authorize @order
  end

  private

  def order_params
    params.require(:order).permit(:quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/burgers/index.html.erb
<h1 class=" burger-title text-center"> My burgers :</h1>
<br>
<br>
<%= render 'burgers/shared/list-burger' %>

app/views/burgers/edit.html.erb
<h2 class= "text-center burger-title">Update your burger :</h2>

<%= render 'burgers/shared/form-burger' %>

app/views/burgers/index.html.erb
<div class="row">
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.5) 0%, rgba(235,87,87,0.2) 50%), url(<%= image_path 'burger.jpg' %>)">
    <div class="banner-content">
        <h1>Home made burger</h1>
        <span id="banner-typed-text"></span>
      </h1>
    </div>
  </div>
</div>
  <!--
      <input id="pac-input" class="controls" type="text" placeholder="Search Box"> -->
<div class ="row background-card">
    <div>
      <div
        id="map"
        style="width: 100%; height: 40vh;"
        data-markers="<%= @markers.to_json %>"
      ></div>
    </div>
  <%= render 'burgers/shared/list-burger' %>
</div>

app/views/burgers/new.html.erb
<h2 class= "text-center burger-title">Create your burger :</h2>
<%= render 'burgers/shared/form-burger' %>

app/views/burgers/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Burgeers
  </div>

 <%= link_to "About the team", about_path(), class: "btn-burgeers" %>
</div>

app/views/burgers/shared/_form-burger.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
   <div class="form-burger">
    <%= simple_form_for @burger do |f| %>
        <% if @burger.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @burger.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <%= f.input :name, label: 'Your name please :', input_html: {class: 'my-input'} %>
      <%= f.input :description, label: 'Description :', input_html: {class: 'my-input'} %>
      <%= f.input :price, label: 'How much do you want to sale it ?', input_html: {class: 'my-input'}  %>
      <%= f.input :quantity_max, label: 'How many ?', input_html: {class: 'my-input'}  %>
      <%= f.input :opening_days, collection: Burger::WEEK_DAYS , label: 'Days you can cook :', input_html: {class: 'my-input'} %>
      <%= f.input :published%>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <div class="inline"><%= f.submit class: "btn-push" %>
        <%= link_to "Home", root_path(), {class: "btn-burgeers"} %></div>
      <% end %>


       </div>
    </div>
</div>

app/views/burgers/shared/_list-burger.html.erb
<div class="row">
  <% @burgers.each do |burger| %>

    <div class="col-xs-12 col-sm-4">
        <%= link_to burger_path(burger) do %>

            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path burger.photo { |n|  } %>)">

                <div class="card-user"> <%= burger.name %> </div>
                <div class="card-price"> <%= burger.price %>$ </div>

                <div class="card-description"> <%= burger.description %> </div>
            </div>
        <% end %>
    </div>

  <% end %>
</div>

app/views/burgers/show.html.erb
<div class="row white-backgroud" >
  <div class = "menu-show">
    <!-- GOING BACK TO THE BURGER LIST -->
    <%= link_to "Back to the list", root_path(), {class: "btn-burgeers"} %>
    <% if policy(@burger).destroy? %>
      <%= link_to "Delete", burger_path(@burger), method: :delete, class: "btn-burgeers" %>
    <% end %>
    <% if policy(@burger).edit? %>
      <%= link_to "Update your burger", edit_burger_path(@burger), class: "btn-burgeers" %>
    <% end %>
    <% if @burger.quantity_max != 0 %>
      <%= link_to "Order !", new_burger_order_path(@burger), {class: "btn-push"} %>
    <% end %>
  </div>
</div>

<div class="row white-backgroud">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <% if @burger.quantity_max != 0 %>
       <%= render 'orders/new', burger: @burger %>
     <% end %>
   </div>
</div>


<div class="row background-card">
  <div class="col-xs-12 col-sm-6">
    <% if !@burger[:photo].nil? %>
      <div class = "burger-photo"> <%= cl_image_tag @burger.photo, height: 300, width: 400, crop: :fill %></div>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-6">
    <div class="row">
      <h1> 🍔 <%= @burger.name.capitalize %></h1>
    </div>
    <div class="row">
      <p> 🍴 Cooker : <%= @burger.user.last_name %> <%= @burger.user.first_name %></p>
    </div>
    <div class="row">
      <p> 💲 Price : <%= @burger.price %></p>
    </div>
    <div class="row">
      <p> 📝 Description : <%= @burger.description %></p>
    </div>
    <div class="row">
      <p> 📦 Stock : <%= @burger.quantity_max %></p>
    </div>
    <div class="row">
      <p> 📆 Opening days : <%= @burger.opening_days %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class = "margin-map"
    id="map"
    style="width: 100%; height: 30vh;"
    data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Burgeers
  </div>

  <%= link_to "About the team", about_path, class: "btn-burgeers" %>
</div>

app/views/layouts/_navbar.html.erb
<div class="row">
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "burgerlogo.png", class: "btn-home", height: 80 %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>
    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <%= link_to "Add a burger", new_burger_path, method: :get, class: "btn-burgeers" %>
      <% if user_signed_in? %>

        <!-- Links when logged in -->


        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id:"navbar-wagon-menu", "data-toggle".to_sym => "dropdown"  %>

            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to admin_burgers_path do %>
                  <i class="fas fa-utensils"></i> <%= t(".profile", default: "My cooked burgeers") %>
                <% end %>
              </li>
              <li>
                <%= link_to orders_path() do %>
                  <i class="fas fa-shopping-basket"></i>  <%= t(".settings", default: "My ordered burgeers") %>
                <% end %>
              </li>
              <li>
                <%= link_to mine_orders_path() do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "My clients orders ") %>
                <% end %>
              </li>

              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="fas fa-edit"></i></i>  <%= t(".sign_out", default: "Edit my profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path(), method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>

            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>BURGEERS</title>
      <%= csrf_meta_tags %>
      <%= action_cable_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all' %>
      <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    </head>

    <body>
      <%= render 'layouts/flashes' %>
      <div class="container">
        <%= render "layouts/navbar" %>
        <%= yield %>
        <%= render "layouts/footer" %>
      </div>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
      <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}&libraries=places" %>
      <%= javascript_pack_tag "map"%>
    </body>
  </html>

app/views/orders/_new.html.erb
<%= simple_form_for([@burger, @order]) do |f| %>
  <%= f.input :quantity, collection: 1..@burger.quantity_max, label: 'Burger quantity', :input_html=> { class: "form-show" } %>
  <%= f.button :submit, label: 'Order!', class: "btn-push" %>
<% end %>

app/views/orders/index.html.erb
<h1 class = "burger-title text-center"> Basket : </h1>

<%= render 'orders/shared/list_orders' %>

app/views/orders/index_cooker_orders.html.erb
<h1 class = "burger-title text-center"> Cooker's orders</h1>

<%= render 'orders/shared/list_orders' %>

app/views/orders/new.html.erb
<div class="row">
  <div class="class= col-xs-6 col-xs-offset-3">

    <div class="form-burger">
      <%= form_for [@burger, @order], :html => { :class => 'form-inline' } do |f| %>
        <%= f.label :quantity, 'How many burger ?', input_html: {class: 'my-input'} %>
        <%= f.text_field :quantity %>
        <%= f.submit class: "btn-push" %>
       <% end %>
    </div>
  </div>
</div>

app/views/orders/shared/_list_orders.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% @orders.each do |order| %>
      <div class="message">
        <%= image_tag order.burger.photo, class: "photo-order"%>
        <div class="message-name burger-title">
          <%= order.quantity %> <%= order.burger.name %>
        </div>
        <div class="message-body burger-title-2">
          <%= order.delivered ? "🚀 Livré" : "🚀 En cours de livraison" %>
          <%= order.user.first_name %>
        </div>
        <div class="message-body">
          <p class="status pending">Pending</p>
          <%= order.total_price %> €
        </div>
        <div>


          <% if request.original_url.include?("mine") %>
            <%= simple_form_for order do |f| %>
              <% if order.errors.any? %>
                <div class="errors-container">
                  <ul>
                    <% @order.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <%= f.submit class: "btn-push" %>
            <% end %>
          <% end %>



        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<h2 class= "text-center burger-title"> Your order :</h2>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
   <div class=" text-center form-burger">
    <p>You ordered <strong><%=@order.quantity %></strong> <%= @order.burger.name %> 🍔 </p>
    <p>Prix total : <strong><%= @order.total_price %> €</strong> 💶</p>
    <p><%= @order.delivered ? "👍 delivered" : "🚀 We are cooking your burger, we should be ready soon" %></p>
    <br>

<!-- rajouter lien vers index -->


    <%= link_to "Your basket", orders_path(), {class: "btn-push"} %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
    <div class="about-title">
      <h2> THE AMAZING TEAM </h2>
    </div>

    <div class="profile text-center">

    <div class="stat">
      <div class="stat-content">
        <%= image_tag "chloe.jpg", height: 100, class: 'about-avatar' %>
        <h3>CHLOE</h3>
        <p>Trello first</p>
        <div class="smiley">🍅</div>
      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <%= image_tag "ismet.jpg", height: 100, class: 'about-avatar' %>
        <h3>ISMET</h3>
        <p>Full stack</p>
        <div class="smiley">🍟</div>
      </div>
    </div>


    <div class="stat">
      <div class="stat-content">
        <%= image_tag "laurie.jpg", height: 100, class: 'about-avatar' %>
        <h3>LAURIE</h3>
        <p>Back end</p>
        <div class="smiley">🥗</div>
      </div>
    </div>

    <div class="stat">
      <div class="stat-content">
        <%= image_tag "paul.jpg", height: 100, class: 'about-avatar' %>
        <h3>PAUL</h3>
        <p>Front end</p>
        <div class="smiley">🥓</div>
      </div>
    </div>

    <div class="team">
      <h6>More about Burgeers</h6>
      <p class="text-justify">
        The team is born with love of food porn or home made things.</p>
      <p class="text-justify">We love to proposes a great product for a happy belly. 🤪</p>
      <p class="text-justify strong">Cooking is all about people. Food is maybe the only universal thing that really has the power to bring everyone together. No matter what culture, everywhere around the world, people get together to eat.
      <p class="text-justify">Guy Fieri</p>
    </div>

    <div class="video-container">
        <%= video_tag 'burgeers.mp4',  autoplay: true, loop: true %>
    </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Places Searchbox</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      .controls {
        margin-top: 10px;
        border: 1px solid transparent;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        height: 32px;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
      }

      #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 300px;
      }

      #pac-input:focus {
        border-color: #4d90fe;
      }

      .pac-container {
        font-family: Roboto;
      }

      #type-selector {
        color: #fff;
        background-color: #4d90fe;
        padding: 5px 11px 0px 11px;
      }

      #type-selector label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }
      #target {
        width: 345px;
      }
    </style>
  </head>
  <body>
    <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div id="map"></div>
    <script>
      // This example adds a search box to a map, using the Google Place Autocomplete
      // feature. People can enter geographical searches. The search box will return a
      // pick list containing a mix of places and predicted search terms.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -33.8688, lng: 151.2195},
          zoom: 13,
          mapTypeId: 'roadmap'
        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places&callback=initAutocomplete"
         async defer></script>
  </body>
</html>